version: "3"
services:
  agileone-api:
    container_name: agileone-api
    build: .
    ports:
      - "9000:9000"
    volumes:
      - .:/app
  #   links:
  #     - mongo
  # mongo:
  #   image: mongo:latest
  #   container_name: mongo
  #   ports:
  #     - "80:80"
  #   environment:
  #     MONGO_INITDB_DATABASE: agileone-db
  #   volumes:
  #     - data-volume:/data/db
volumes:
  data-volume:
